apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clearml-agent.fullname" . }}
  labels:
    {{- include "clearml-agent.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}