apiVersion: v1
metadata:
  namespace: clearml-agent
spec:
  containers:
  - resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 1
        memory: 4Gi
  restartPolicy: Never
